on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Build
        run: |
          make bbgo-slim-linux-amd64
          tar zcf build/bbgo-slim-linux-amd64.tgz build/bbgo/bbgo-slim-linux-amd64
          make bbgo-slim-linux-arm64
          tar zcf build/bbgo-slim-linux-arm64.tgz build/bbgo/bbgo-slim-linux-arm64
          make bbgo-slim-darwin-amd64
          tar zcf build/bbgo-slim-darwin-amd64.tgz build/bbgo/bbgo-slim-darwin-amd64
          make bbgo-slim-darwin-arm64
          tar zcf build/bbgo-slim-darwin-arm64.tgz build/bbgo/bbgo-slim-darwin-arm64
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: BBGO ${{ github.ref }}
          body: |
            TODO: Fill changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Upload Linux amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/bbgo-slim-linux-amd64.tgz
          asset_name: bbgo-slim-${{ github.ref }}-linux-amd64.tgz
          asset_content_type: application/octet-stream
      - name: Upload Linux arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/bbgo-slim-linux-arm64.tgz
          asset_name: bbgo-slim-${{ github.ref }}-linux-arm64.tgz
          asset_content_type: application/octet-stream
      - name: Upload Darwin amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/bbgo-slim-darwin-amd64.tgz
          asset_name: bbgo-slim-${{ github.ref }}-darwin-amd64.tgz
          asset_content_type: application/octet-stream
      - name: Upload Darwin arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/bbgo-slim-darwin-arm64.tgz
          asset_name: bbgo-slim-${{ github.ref }}-darwin-arm64.tgz
          asset_content_type: application/octet-stream
